config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy]
    post "cart_items/cancel", as: "cancel"
    get "orders/completion", as: "completion"
    get "orders/:id/confirmation" => "orders#confirmation", as: "confirmation"
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:new, :edit, :create, :update]
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :integer          not null, primary key
#  introduction :string
#  name         :string
#  price        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  genre_id     :integer          not null
#
# Indexes
#
#  index_items_on_genre_id  (genre_id)
#
# Foreign Keys
#
#  genre_id  (genre_id => genres.id)
#
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :customers, through: :cart_items
  has_many :order_items, dependent: :destroy
  belongs_to :genre
  has_one_attached :image

  def with_tax_price
    (price.to_i * 1.1).floor
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    item = Item.create(item_params)
    redirect_to item_path(item)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to item_path(item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :image)
  end
end

app/helpers/admin/item_helper.rb
module Admin::ItemHelper
end

app/views/admin/items/edit.html.erb
<h1>商品更新</h1>
<h2><%= @item.name %></h2>
<%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
<div>
  <%= f.label :name, "商品" %>
  <%= f.text_field :name, placeholder: "商品名" %>
</div>
<div>
  <%= f.label :introduction %>
  <%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %>
</div>

<dev>
  <%= f.label :image %>
  <%= f.file_field :image, accept: "image/*" %>
</dev>

<div>
  <%= f.label :genre_id, "ジャンル" %>
  <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name, selected: @item.genre.id) %>
</div>

<div>
  <%= f.label :price %>
  <%= f.number_field :price, placeholder: 1000 %>
</div>

  <%= f.submit "登録" %>

<% end %>

app/views/admin/items/new.html.erb
<h1>商品登録</h1>
<%= form_with model: @item, url: admin_items_path do |f| %>
<div>
  <%= f.label :name, "商品" %>
  <%= f.text_field :name, placeholder: "商品名" %>
</div>
<div>
  <%= f.label :introduction %>
  <%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %>
</div>

<dev>
  <%= f.label :image %>
  <%= f.file_field :image, accept: "image/*" %>
</dev>

<div>
  <%= f.label :genre_id, "ジャンル" %>
  <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), option = { include_blank: "--選択してください--" } %>
</div>

<div>
  <%= f.label :price %>
  <%= f.number_field :price, placeholder: 1000 %>
</div>

  <%= f.submit "登録" %>

<% end %>