config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy]
    post "cart_items/cancel", as: "cancel"
    get "orders/completion", as: "completion"
    get "orders/:id/confirmation" => "orders#confirmation", as: "confirmation"
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:new, :edit, :create, :update]
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id             :integer          not null, primary key
#  address        :string           not null
#  code           :integer
#  name           :string           not null
#  order_status   :integer          default("waiting")
#  payment_method :integer
#  total_price    :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  customer_id    :integer          not null
#
# Indexes
#
#  index_orders_on_customer_id  (customer_id)
#
# Foreign Keys
#
#  customer_id  (customer_id => customers.id)
#
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirmation: 1, production: 2, preparation: 3, done: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])

  end

  def update
      @order = Order.find(params[:id])
      @order.update(order_status_params)
      if params[:order][:order_status] == "confirmation"
        @order.order_items.each do |order_item|
          order_item.update(production_status: "waiting_production")
        end
      end
      redirect_to request.referer
  end

  private

  def order_status_params
    params.require(:order).permit(:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div>
  <%= @order.customer.name %>
</div>
<div>
  <%= @order.created_at %>
</div>
<div>
  <%= @order.code %>
  <%= @order.address %>
</div>
<div>
  <%= @order.name %>
</div>
<div>
  <%= @order.payment_method_i18n %>
</div>
<%= form_with model: @order, url: admin_order_path(@order) do |f| %>
  <%= f.select :order_status, Order.order_statuses.keys.map{ |k| [t("enums.order.order_status.#{k}"),k]} %>
  <%= f.submit "変更" %>
<% end %>

<% @order.order_items.each do |order_item| %>
  <%= form_with model: order_item, url: admin_order_item_path(order_item) do |f| %>
  <%= f.select :production_status, OrderItem.production_statuses.keys.map{ |k| [t("enums.order_item.production_status.#{k}"),k]} %>
  <%= f.submit "変更" %>
  <% end %>
<% end %>