config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy]
    post "cart_items/cancel", as: "cancel"
    get "orders/completion", as: "completion"
    get "orders/:id/confirmation" => "orders#confirmation", as: "confirmation"
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
    resources :items, only: [:new, :edit, :create, :update]
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>

  <body>
    <%= link_to "顧客サインアップ", new_customer_registration_path %>
    <%= link_to "顧客ログイン", new_customer_session_path %>
    <%= link_to "顧客ログアウト", destroy_customer_session_path, method: :delete %>
    <%= link_to "管理者ログイン", new_admin_session_path %>
    <%= link_to "　", items_path, style: "text-decoration: none;" %>
    <%= link_to "カート", cart_items_path %>
    <%= link_to "顧客一覧", admin_path %>
    <%= link_to "商品追加", new_admin_item_path %>
    <%= link_to "住所一覧", addresses_path %>
    <%= link_to "トップ", root_path %>
    <% if customer_signed_in? %>
      <h1><%= current_customer.id %></h1>
    <% end %>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <%= yield %>
  </body>
</html>